import os
from dotenv import load_dotenv
from typing import List 
from pydantic import BaseModel, Field

load_dotenv()
from langchain.agents import create_agent
from langchain.tools import tool
from langchain_core.messages import HumanMessage
from langchain_openai import ChatOpenAI
from tavily import TavilyClient
from langchain_tavily import TavilySearch

tavily = TavilyClient() 

@tool
def search(query: str) -> str:
    """
    Tool that searches for the current weather in a given city.

    Args:
        query (str): The city to search the weather for.
    Returns:
        str: The current weather in the given city.
    """
    print(f"Searching for: {query}")
    #return "Seoul weather is sunny"
    return tavily.search(query=query)

class Source(BaseModel):
    """
    Schema for a source used by agent
    """

    url:str = Field(description="The URL of the source")

class AgentResponse(BaseModel):
    """Schema for agent response with answer and sources"""
    asnwer: str = Field(description="The answer generated by the agent")
    sources: List[Source] = Field(default_factory=list, description="The list of sources to generate the answers")


llm = ChatOpenAI(model="gpt-5")
tools = [TavilySearch()]
agent = create_agent(model = llm, tools=tools)


def main():
    print("Hello from langchain-session!")
    result = agent.invoke({"messages": HumanMessage(content="Search for 3 job posting for AI Engineer in Seoul from LinkedIn")})
    print(result)
if __name__ == "__main__":
    main()
